---
- name: Create shared Docker network for Traefik reverse proxy
  community.docker.docker_network:
    name: traefik_reverse_proxy
    driver: bridge
    state: present
    attachable: yes
  become: true
  tags:
    - network
    - always