---
- name: Create shared Docker network for Traefik reverse proxy
  community.docker.docker_network:
    name: traefik_reverse_proxy
    driver: bridge
    state: present
    attachable: yes
    enable_ipv6: no
    ipam_options:
      subnet: "172.20.0.0/16"
  become: true
  tags:
    - network
    - always